''' Copyright start
  Copyright (C) 2008 - 2023 Fortinet Inc.
  All rights reserved.
  FORTINET CONFIDENTIAL & FORTINET PROPRIETARY SOURCE CODE
  Copyright end '''

attribute_mapping = {
            'Destination Port': 'destIpPort IN ({0})',
            'Destination IP': 'destIpAddr IN ({0})',
            'Event ID': 'eventId IN ({0}) AND phEventCategory &gt;= 0',
            'Event Action': 'eventAction = {0}',
            'Incident ID': 'phEventCategory = 1  AND  incidentId IN ({0})',
            'File Name': 'fileName CONTAIN "{0}"',
            'Host Name': 'hostName CONTAIN "{0}"',
            'Organization Name': 'customer CONTAIN "{0}"',
            'Process Name': 'procName CONTAIN "{0}"',
            'Post-NAT Source IP': 'postNATSrcIpAddr IN ({0})',
            'Raw Event Log': 'rawEventMsg CONTAIN "{0}"',
            'Relay IP': 'relayDevIpAddr IN ({0})',
            'Reporting IP': 'reptDevIpAddr IN ({0})',
            'Source IP': 'srcIpAddr IN ({0})',
            'Source Port': 'srcIpPort IN ({0})',
            'Source MAC': 'srcMACAddr CONTAIN "{0}"',
            'User': 'user CONTAIN "{0}"'
}

attribute_list = {
    'Event Type': 'eventType',
    'Event Severity': 'eventSeverity',
    'IPS Event Risk Rating': 'ipsEvRR',
    'IPS Event Threat Rating': 'ipsEvTR',
    'Event Action': 'eventAction',
    'Device Time': 'deviceTime',
    'Event Receive Time': 'phRecvTime',
    'Relaying IP': 'relayDevIpAddr',
    'Reporting IP': 'reptDevIpAddr',
    'Relaying Device': 'relayDevName',
    'Reporting Device': 'reptDevName',
    'Organization ID': 'phCustId',
    'Raw Event Log': 'rawEventMsg',
    'Event ID': 'eventId',
    'System Event Category': 'phEventCategory',
    'Agent ID': 'phAgentId',
    'Event Occur Time': 'eventTime',
    'Event Name': 'eventName',
    'Event Parse Status': 'eventParsedOk',
    'Event Severity Category': 'eventSeverityCat',
    'Incident Source': 'incidentSrc',
    'Incident Target': 'incidentTarget',
    'Business Service Name': 'bizService',
    'Incident Trigger Attribute List': 'triggeringAttrList',
    'Event Description': 'eventDesc',
    'Informational URL': 'infoURL',
    'Incident Reporting IP': 'incidentRptIp',
    'Reporting Vendor': 'reptVendor',
    'Reporting Model': 'reptModel',
    'Host Vendor': 'hostVendor',
    'Host Model': 'hostModel',
    'False Positive Check': 'ipsFPCheckStatus',
    'Organization Name': 'customer',
    'Application Port': 'appPort',
    'Incident ID': 'incidentId',
    'Incident Title': 'incidentTitle',
    'Collector Name': 'phCollectorName',
    'Incident Category': 'phIncidentCategory',
    'Event Source': 'eventSource',
    'Rule Name': 'ruleName',
    'Snort Event ID': 'snortEventId',
    'Collector ID': 'collectorId',
    'Collector IP': 'collectorIp',
    'Employee ID': 'employeeId',
    'Account Number': 'phAccountNum',
    'Source IP ': 'srcIpAddr',
    'Destination IP': 'destIpAddr',
    'Destination Host Name': 'destName',
    'Post-NAT Source IP': 'postNATSrcIpAddr',
    'Pre-NAT Destination IP': 'preNATDestIpAddr',
    'Host IP': 'hostIpAddr',
    'Host Name': 'hostName',
    'Source MAC': 'srcMACAddr',
    'Destination MAC': 'destMACAddr',
    'Host MAC': 'hostMACAddr',
    'IP Protocol': 'ipProto',
    'Source TCP/UDP Port': 'srcIpPort',
    'Destination TCP/UDP Port': 'destIpPort',
    'Post-NAT Source Port': 'postNATSrcIpPort',
    'Pre-NAT Destination Port': 'preNATDestIpPort',
    'ICMP Type': 'icmpType',
    'ICMP Code': 'icmpCode',
    'TCP flags': 'tcpFlags',
    'Source Autonomous System Number': 'srcASNum',
    'Destination Autonomous System Number': 'destASNum',
    'Source VLAN': 'srcVLAN',
    'Destination VLAN': 'destVLAN',
    'Source Interface Name': 'srcIntfName',
    'Destination Interface Name': 'destIntfName',
    'Host Interface Name': 'intfName',
    'Source Device Port': 'srcDevPort',
    'Destination Device Port': 'destDevPort',
    'Network Access Device IP': 'nepDevIpAddr',
    'Network Access Device Port': 'nepDevPort',
    'Source Interface SNMP Index': 'srcSnmpIntfIndex',
    'Destination Interface SNMP Index': 'destSnmpIntfIndex',
    'IP Type of Service': 'tos',
    'Sent Packets': 'sentPkts',
    'Received Packets': 'recvPkts',
    'Total Packets': 'totPkts',
    'Sent Bytes': 'sentBytes',
    'Received Bytes': 'recvBytes',
    'Total Bytes': 'totBytes',
    'Duration': 'durationMSec',
    'Connection Id': 'ipConnId',
    'Firewall Session': 'fwConnCount',
    'Firewall Session Utilization': 'fwConnPct',
    'Recv Packet Errors': 'inIntfPktErr',
    'Sent Packet Errors': 'outIntfPktErr',
    'Recv Packet Error Pct': 'inIntfPktErrPct',
    'Sent Packet Error Pct': 'outIntfPktErrPct',
    'Recv Interface Util': 'inIntfUtil',
    'Sent Interface Util': 'outIntfUtil',
    'Network Access Device': 'nepDevName',
    'Host VLAN': 'hostVLAN',
    'Device Port': 'devPort',
    'WLAN Channel Id': 'wlanChannelId',
    'WLAN Radio Id': 'wlanRadioId',
    'WLAN SSID': 'wlanSSID',
    'Target Host MAC': 'targetHostMACAddr',
    'Sent TCP flags': 'srcDestTCPFlags',
    'Auth Server IP': 'authServerIpAddr',
    'Auth Server Name': 'authServerName',
    'Source Host Name': 'srcName',
    'Source Firewall Zone': 'srcFwZone',
    'Destination Firewall Zone': 'destFwZone',
    'Wireless Attack Signature Name': 'wirelessSigName',
    'IP Port': 'ipPort',
    'Palo Alto Firewall Action': 'paFwAction',
    'VPN Tunnel Name': 'vpnTunnelName',
    'FQDN': 'fqdnName',
    'Host Virtual IP': 'hostVirtIpAddr',
    'Previous Source IP': 'prevSrcIpAddr',
    'Previous Source TCP/UDP Port': 'prevSrcIpPort',
    'Server Name': 'serverName',
    'Type': 'type',
    'Image File': 'imageFile',
    'Firewall Action': 'fwAction',
    'Recv Auth Fail': 'recvAuthFail',
    'Destination TOS': 'dstTos',
    'Command and Control TCP/UDP Port': 'cncPort',
    'Source TOS': 'srcTos',
    'Checksum': 'checksum',
    'ICMP Id': 'icmpId',
    'VPN Status': 'vpnStatus',
    'IP Version': 'ipVersion',
    'Server IP': 'serverIpAddr',
    'New Host IP': 'newHostIpAddr',
    'DHCP Request Type': 'dhcpReqType',
    'DHCP Gateway': 'dhcpGateway',
    'DNS Server IP': 'dnsServer',
    'DNS Query Type': 'dnsQueryType',
    'TCP Connection': 'tcpFwConnCount',
    'UDP Connection': 'udpFwConnCount',
    'ICMP Connection': 'icmpFwConnCount',
    'VPN Conn Type': 'vpnConnType',
    'Hash Algorithm': 'hashAlgo',
    'ARP Source MAC': 'arpSrcMACAddr',
    'ARP Destination MAC': 'arpDestMACAddr',
    'ARP Source IP': 'arpSrcIpAddr',
    'ARP Destination IP': 'arpDestIpAddr',
    'Command and Control Host Name': 'cncName',
    'DHCP Server MAC': 'dhcpServerMacAddr',
    'Destination Service Name': 'destServiceName',
    'Post-NAT Destination IP': 'postNATDestIpAddr',
    'Post-NAT Destination Ip Port': 'postNATDestIpPort',
    'Computer': 'computer',
    'Target Computer': 'targetComputer',
    'Domain': 'domain',
    'Target Domain': 'targetDomain',
    'Operating System': 'osType',
    'Operating System Version': 'osVersion',
    'File Name': 'fileName',
    'Process Name': 'procName',
    'OS Object Type': 'osObjType',
    'Object Name': 'osObjName',
    'Object Handle': 'osObjHandleID',
    'Object Access Type': 'osObjAccessType',
    'Software Name': 'swProcName',
    'Disk Name': 'diskName',
    'UUID': 'uuid',
    'VM IP': 'vmIpAddr',
    'VM Host Name': 'vmHostname',
    'Virus Database Version': 'virdbVer',
    'IDS Database Version': 'idsdbVer',
    'Anti-Virus Extension Database Version': 'avenVer',
    'Extension Database Version': 'extdbVer',
    'WLAN User count': 'wlanUserCount',
    'Host Country': 'hostGeoCountry',
    'Source Country': 'srcGeoCountry',
    'Destination Country': 'destGeoCountry',
    'Reporting Country': 'reptGeoCountry',
    'Host State': 'hostGeoState',
    'Source State': 'srcGeoState',
    'Destination State': 'destGeoState',
    'Reporting State': 'reptGeoState',
    'Host City': 'hostGeoCity',
    'Source City': 'srcGeoCity',
    'Destination City': 'destGeoCity',
    'Reporting City': 'reptGeoCity',
    'Host Organization': 'hostGeoOrg',
    'Source Organization': 'srcGeoOrg',
    'Destination Organization': 'destGeoOrg',
    'Reporting Organization': 'reptGeoOrg',
    'IPS Sensor Id': 'ipsSensorId',
    'File Path': 'filePath',
    'File Owner': 'fileOwner',
    'User Id': 'userId',
    'User': 'user',
    'Target User': 'targetUser',
    'User Group': 'userGrp',
    'Target User Group': 'targetUserGrp',
    'Win Logon Type': 'winLogonType',
    'Win Logon Id': 'winLogonId',
    'Application Name': 'appName',
    'HTTP User Agent': 'httpUserAgent',
    'URI Stem': 'uriStem',
    'URI Query': 'uriQuery',
    'Win Logon Fail Code': 'winLogonFailCode',
    'Mail Sender': 'senderMailAddr',
    'Mail Receiver': 'receiverMailAddr',
    'Mail Subject': 'mailSubject',
    'Malware Name': 'virusName',
    'Malware Type': 'virusType',
    'Malware Action': 'virusAction',
    'Vulnerability Name': 'vulnName',
    'Vulnerability Type': 'vulnType',
    'Vulnerability CVE Id': 'vulnCVEId',
    'Vulnerability Score': 'vulnScore',
    'Attack Name': 'attackName',
    'Message': 'msg'
}
