RESPONSE_FIELDS = {
    "Object ID": "objid",
    "Type": "type",
    "Name": "name",
    "Tags": "tags",
    "Active": "active",
    "Downtime in Percentage": "downtime",
    "Downtime": "downtimetime",
    "Downtime Since": "downtimesince",
    "Uptime in Percentage": "uptime",
    "Uptime": "uptimetime",
    "Uptime Since": "uptimesince",
    "Knowntime": "knowntime",
    "Cumsince": "cumsince",
    "Sensor Name": "sensor",
    "Interval": "interval",
    "Last Check": "lastcheck",
    "Last Up": "lastup",
    "Last Down": "lastdown",
    "Device Name": "device",
    "Group Name": "group",
    "Probe Name": "probe",
    "Group Device": "grpdev",
    "Trigger Type": "notifiesx",
    "Dependency": "dependency",
    "Probe Group Device": "probegroupdevice",
    "Status": "status",
    "Message": "message",
    "Priority": "priority",
    "Last Value": "lastvalue",
    "Up Sensor State": "upsens",
    "Down Sensor State": "downsens",
    "Down Acknowledged Sensor State": "downacksens",
    "Partial Down Sensor State": "partialdownsens",
    "Warnning Sensor State": "warnsens",
    "Paused Sensor State": "pausedsens",
    "Unusual Sensor State": "unusualsens",
    "Undefined Sensor State": "undefinedsens",
    "Total Sensor": "totalsens",
    "Number of Groups": "groupnum",
    "Number of Devices": "devicenum",
    "Value": "value",
    "Coverage": "coverage",
    "Favorite": "favorite",
    "User": "user",
    "Parent": "parent",
    "Datetime": "datetime",
    "Date Only": "dateonly",
    "time Only": "timeonly",
    "Schedule": "schedule",
    "Period": "period",
    "Last Run": "lastrun",
    "Size": "size",
    "Comments": "comments",
    "Host": "host",
    "Base Type": "basetype",
    "Base Link": "baselink",
    "Parent ID": "parentid",
    "Location": "location",
    "Fold": "fold",
    "Ticket Type": "tickettype",
    "Modified By": "modifiedby",
    "Actions": "actions",
    "Content": "Content"
}

CONTENT_TYPE = {"Devices": "devices",
                "Sensors": "sensors",
                "Tickets": "tickets",
                "Ticket Data": "ticketdata",
                "Messages": "messages",
                "Channels": "channels",
                "Reports": "reports",
                "Top Lists": "toplists",
                "Sys Info": "sysinfo",
                "Stored Reports": "storedreports",
                }

DURATIONS = {"Today": "today",
             "Yesterday": "yesterday",
             "One Week": "7days",
             "One Month": "30days",
             "Six Months": "6months",
             "One Year": "12months"}

FILTER_STATUS = {"Unknown": 1,
                 "Collecting": 2,
                 "Up": 3,
                 "Warning": 4,
                 "Down": 5,
                 "No Probe": 6,
                 "Paused by User": 7,
                 "Paused by Dependency": 8,
                 "Paused by Schedule": 9,
                 "Unusual": 10,
                 "Paused by License": 11,
                 "Paused Until": 12,
                 "Down Acknowledged": 13,
                 "Down Partial": 14}

ACK_DURATION = {
    "For 5 Minutes": 5,
    "For 15 Minutes": 15,
    "For 1 Hour": 60,
    "For 3 Hours": 180,
    "For 1 Day": 1440

}
SUPPORTED_OBJECT = ["Group", "Probe", "Device", "Sensor"]
