cs_imap_1 = "CS-IMAP-1: Socket Binding on ' {0}::{1} ' failed with Error :: {2}"
cs_imap_2 = "CS-IMAP-2: {0} is mandatory arguments"
cs_imap_3 = "CS-IMAP-3: Invalid function argument"
cs_imap_4 = "CS-IMAP-4: Notification Service already running for server {0}:{1} and user {2} "
cs_imap_5 = "CS-IMAP-5: Exception occurred while creating or starting notification service."
cs_imap_6 = "CS-IMAP-6: Notification service terminated unexpectedly for username {0}"
cs_imap_7 = "CS-IMAP-7: Retrying {0} time... Exception occurred while starting IMAP Idle mode. Exception :: {1}"
cs_imap_8 = "CS-IMAP-8: Error occurred while starting IMAP Idle mode for username ' {0} ' ERROR :: {1}"
cs_imap_9 = "CS-IMAP-9: Error occurred in notification service while listening mailbox ERROR :: {0}"
cs_imap_10 = "CS-IMAP-10: Invalid arguments sent. Error Occurred while parsing the arguments"
cs_imap_11 = "CS-IMAP-11: Error occurred while getting the private or public key. File not found for keys. ERROR :: {0}"
cs_imap_12 = "CS-IMAP-12: Notification Service not running for server {0}:{1} user {2}. " \
             "Deactivate and activate the connector to restart the listeners."
cs_imap_13 = "CS-IMAP-13: Notification Service is already stopped for server {0}:{1} and user {2}"
cs_imap_14 = "CS-IMAP-14: Error while authenticating the mailbox. Invalid Username or Password"
cs_imap_15 = "CS-IMAP-15: Error in bringing up notification service"
cs_imap_16 = "CS-IMAP-16: Notification service is down. Deactivate and activate the connector to restart the service"
cs_imap_17 = "CS-IMAP-17: Notification service is already down, bringing up the service"
cs_imap_18 = "CS-IMAP-18: Exception occurred while logging out the IMAP client. ERROR :: {0}"
cs_imap_19 = "CS-IMAP-19: Exception occured while creating the the IMAP client for username {0}. " \
             "Please check the 'Use TLS' and 'Verify SSL' option"
cs_imap_20 = "CS-IMAP-20: Error occured in connecting to server {}"